spring.application.name=hirely-backend


# PostgresSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/job_board_db
spring.datasource.username=postgres
spring.datasource.password=GoodGod
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.\PostgreSQLDialect



security.jwt.secret-key=HWAu6wdp2NCKbrxHxj5zgdRgsORKa8ld632byrI21FY=
security.jwt.expiration-time=86400000